// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShQj1mxiJTPBlvaBAUYjy6s3DKOE2b-Y',
    appId: '1:537238582806:web:b42eecfb659ca3e0076737',
    messagingSenderId: '537238582806',
    projectId: 'prac-app-b997d',
    authDomain: 'prac-app-b997d.firebaseapp.com',
    storageBucket: 'prac-app-b997d.appspot.com',
    measurementId: 'G-8DHLQJJBXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnHPbLKk9tK0zBCWynADzLFPfW3GoLT8',
    appId: '1:537238582806:android:fb81f1a3ff229b0c076737',
    messagingSenderId: '537238582806',
    projectId: 'prac-app-b997d',
    storageBucket: 'prac-app-b997d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZxU6i3VeBFq46fl2k7f9oRNLtfz3NVMk',
    appId: '1:537238582806:ios:21f0d4f7b1d19ca1076737',
    messagingSenderId: '537238582806',
    projectId: 'prac-app-b997d',
    storageBucket: 'prac-app-b997d.appspot.com',
    iosClientId: '537238582806-vkt9bgbho5bf64spgsahpv97f8o37627.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZxU6i3VeBFq46fl2k7f9oRNLtfz3NVMk',
    appId: '1:537238582806:ios:21f0d4f7b1d19ca1076737',
    messagingSenderId: '537238582806',
    projectId: 'prac-app-b997d',
    storageBucket: 'prac-app-b997d.appspot.com',
    iosClientId: '537238582806-vkt9bgbho5bf64spgsahpv97f8o37627.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
